export interface HarloweWrapper {
	after: string;
	before: string;
	placeholder?: string;
}

export type HarloweAlignment = 'center' | 'justify' | 'left' | 'right';

function greatestCommonDivisor(left: number, right: number): number {
	return left
		? right
			? greatestCommonDivisor(right, left % right)
			: left
		: right;
}

function quoted(value: string) {
	return JSON.stringify(value);
}

function placementMarker(placement: number, width: number) {
	const widthFraction = width / 10;
	const empty = 1 - widthFraction;
	const left = Math.round(100 * empty * (placement / 10));
	const middle = Math.round(100 * widthFraction);
	const right = Math.round(100 * empty * (1 - placement / 10));
	const divisor =
		greatestCommonDivisor(middle, greatestCommonDivisor(left, right)) || 1;

	return {
		box: `${'='.repeat(left / divisor)}${'X'.repeat(
			middle / divisor
		)}${'='.repeat(right / divisor)}`,
		left: left / 100,
		right: right / 100,
		width: middle / 100
	};
}

/**
 * Reproduces the two source forms generated by Harlowe 3.3.9's alignment
 * panel: compact alignment markup when possible, otherwise (align:)+(box:).
 */
export function harloweAlignmentWrapper({
	alignment,
	placement,
	remainder,
	width
}: {
	alignment: HarloweAlignment;
	placement: number;
	remainder: boolean;
	width: number;
}): HarloweWrapper {
	const box = placementMarker(placement, width);
	const canUseAlignmentMarkup =
		box.width === (alignment === 'center' ? 0.5 : 1) &&
		(!box.left || !box.right) ===
			(alignment !== 'center' && alignment !== 'justify');

	if (canUseAlignmentMarkup) {
		const left = Math.round(10 * box.left);
		const right = Math.round(10 * box.right);
		const divisor = greatestCommonDivisor(left, right) || 1;
		const marker =
			alignment === 'left'
				? '<=='
				: alignment === 'right'
					? '==>'
					: `${'='.repeat(left / divisor)}${left ? '>' : ''}${
							right ? '<' : ''
						}${'='.repeat(right / divisor)}`;

		return remainder
			? {after: '', before: `${marker}\n`, placeholder: 'Aligned Text'}
			: {
					after: ']',
					before: `(align:${quoted(marker)})[`,
					placeholder: 'Aligned Text'
				};
	}

	const marker: Record<HarloweAlignment, string> = {
		center: '=><=',
		justify: '<==>',
		left: '<==',
		right: '==>'
	};
	const changer = `(align:${quoted(marker[alignment])})+(box:${quoted(
		box.box
	)})`;

	return {
		after: remainder ? '' : ']',
		before: `${changer}${remainder ? '[=\n' : '['}`,
		placeholder: 'Aligned Text'
	};
}

function fourDecimals(value: number) {
	return Math.round(10000 * value) / 10000;
}

/** Converts the colour/opacity controls to the same Harlowe value forms as CM5. */
export function harloweColour(colour: string, opacity: number) {
	const normalized = colour.toLowerCase();

	if (opacity === 0) {
		return 'transparent';
	}

	if (opacity >= 1) {
		return normalized[1] === normalized[2] &&
			normalized[3] === normalized[4] &&
			normalized[5] === normalized[6]
			? `#${normalized[1]}${normalized[3]}${normalized[5]}`
			: normalized;
	}

	const red = Number.parseInt(normalized.slice(1, 3), 16) / 255;
	const green = Number.parseInt(normalized.slice(3, 5), 16) / 255;
	const blue = Number.parseInt(normalized.slice(5, 7), 16) / 255;
	const max = Math.max(red, green, blue);
	const min = Math.min(red, green, blue);
	const lightness = (max + min) / 2;
	const delta = max - min;
	let hue = 0;
	let saturation = 0;

	if (max !== min) {
		saturation =
			lightness > 0.5 ? delta / (2 - max - min) : delta / (max + min);
		hue =
			max === red
				? (green - blue) / delta + (green < blue ? 6 : 0)
				: max === green
					? (blue - red) / delta + 2
					: (red - green) / delta + 4;
		hue = Math.round(60 * hue);
	}

	return `(hsl:${fourDecimals(hue)},${fourDecimals(
		saturation
	)},${fourDecimals(lightness)},${fourDecimals(opacity)})`;
}

export function harloweInputBoxSource({
	binding,
	forced,
	initialText,
	placement,
	rows,
	width
}: {
	binding?: string;
	forced: boolean;
	initialText: string;
	placement: number;
	rows: number;
	width: number;
}) {
	const box = placementMarker(placement, width);
	const name = forced ? 'force-input-box' : 'input-box';

	return `(${name}:${binding ? `2bind ${binding},` : ''}${quoted(box.box)}${
		rows === 3 ? '' : `,${rows}`
	}${forced || initialText ? `,${quoted(initialText)}` : ''})`;
}

export type HarloweLinkAction = 'cycle' | 'goto' | 'reveal' | 'undo';

export type HarloweRevealBehavior =
	'link' | 'link-repeat' | 'link-rerun' | 'link-reveal';

export function harloweLinkWrapper({
	action,
	arrivingTransition,
	clickPage,
	cycleEnd,
	cycleOptions,
	departingTransition,
	passage,
	remainder,
	revealBehavior,
	revealedTransition,
	text,
	transitionTime
}: {
	action: HarloweLinkAction;
	arrivingTransition: string;
	clickPage: boolean;
	cycleEnd: 'loop' | 'remove' | 'unlink';
	cycleOptions: string[];
	departingTransition: string;
	passage: string;
	remainder: boolean;
	revealBehavior: HarloweRevealBehavior;
	revealedTransition: string;
	text: string;
	transitionTime: number;
}): HarloweWrapper {
	const time = transitionTime === 0.8 ? '' : `(t8n-time:${transitionTime}s)`;

	if (action === 'goto') {
		const link = clickPage
			? `(click-goto:?page,${quoted(passage)})`
			: [']]', '->', '<-'].some(
						part => passage.includes(part) || text.includes(part)
				  )
				? `(link-goto:${quoted(text)},${quoted(passage)})`
				: `[[${text}->${passage}]]`;
		const changers = [
			departingTransition ? `(t8n-depart:${quoted(departingTransition)})` : '',
			arrivingTransition ? `(t8n-arrive:${quoted(arrivingTransition)})` : '',
			time
		].filter(Boolean);

		return {
			after: '',
			before: [...changers, link].join('+'),
			placeholder: ''
		};
	}

	if (action === 'undo') {
		const link = clickPage
			? '(click-undo:?page)'
			: `(link-undo:${quoted(text)})`;
		const changers = [
			departingTransition ? `(t8n-depart:${quoted(departingTransition)})` : '',
			arrivingTransition ? `(t8n-arrive:${quoted(arrivingTransition)})` : '',
			time
		].filter(Boolean);

		return {
			after: '',
			before: [...changers, link].join('+'),
			placeholder: ''
		};
	}

	if (action === 'cycle') {
		const options = [text, ...cycleOptions];
		const macro = cycleEnd === 'loop' ? 'cycling-link' : 'seq-link';

		if (cycleEnd === 'remove') {
			options.push('');
		}

		return {
			after: '',
			before: `(${macro}:${options.map(quoted).join(',')})`,
			placeholder: ''
		};
	}

	const trigger = clickPage
		? '(click:?page)'
		: `(${revealBehavior}:${quoted(text)})`;
	const changers = [
		revealedTransition ? `(t8n:${quoted(revealedTransition)})` : '',
		time,
		trigger
	].filter(Boolean);

	return {
		after: remainder ? '' : ']',
		before: `${changers.join('+')}${remainder ? '[=\n' : '['}`,
		placeholder: 'Revealed Text'
	};
}

const comparisonOperator: Record<string, string> = {
	'at least': ' >= ',
	'at most': ' <= ',
	'anything but': ' is not ',
	exactly: ' is ',
	'a multiple of': ' % '
};

export function harloweVisitComparison(
	left: string,
	comparison: string,
	count: number
) {
	let source = `${left}${comparisonOperator[comparison]}${count}`;

	if (comparison === 'a multiple of') {
		source += ' is 0';
		source = source.replace(' % 2 is 0', ' is an even');
	}

	return source;
}
