// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreExternalChange } from "./CoreExternalChange";

export type CoreExternalDelta = { changes: Array<CoreExternalChange>, };
