// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreHistoryKind } from "./CoreHistoryKind";

export type CoreSessionStatus = { canRedo: boolean, canUndo: boolean, dirty: boolean, redoKind: CoreHistoryKind | null, revision: number, undoKind: CoreHistoryKind | null, };
