// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorePassageLinkFact } from "./CorePassageLinkFact";

export type CoreBacklinksPage = { backlinks: Array<CorePassageLinkFact>, nextCursor: string | null, passageId: string, revision: number, storyId: string, totalCount: number, };
