// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDiagnosticSeverity } from "./CoreDiagnosticSeverity";

export type CoreDiagnosticsQuery = { cursor: string | null, limit: number, severity: CoreDiagnosticSeverity | null, };
