// This file was generated by ts-rs. Do not edit this file manually.
import type { CoreDocumentKind } from "./CoreDocumentKind";
export type CoreDocumentEntry = { kind: CoreDocumentKind, passageId: string | null, text: string, };
