// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreSymbolKind = "variable" | "temporaryVariable" | "hook" | "storyMetadata" | "storyFormat" | "asset";
