// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetInventoryEntry } from "./CoreAssetInventoryEntry";

export type CoreStoryIndexOptions = { fuzzy: boolean, includeAssets: boolean, includeContents: boolean, includeDiagnostics: boolean, includeFiles: boolean, includeGraph: boolean, includePassageNames: boolean, includePassageText: boolean, includeScript: boolean, includeStylesheet: boolean, includeTags: boolean, includeVariables: boolean, matchCase: boolean, query: string | null, replacement: string | null, useRegexes: boolean, knownAssets: Array<CoreAssetInventoryEntry>, };
