// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetReference } from "./CoreAssetReference";
import type { CoreContentsEntry } from "./CoreContentsEntry";
import type { CoreDiagnostic } from "./CoreDiagnostic";
import type { CoreGraphStats } from "./CoreGraphStats";
import type { CoreReplacePreview } from "./CoreReplacePreview";
import type { CoreSearchHit } from "./CoreSearchHit";
import type { CoreSourceFile } from "./CoreSourceFile";
import type { CoreSymbol } from "./CoreSymbol";
import type { CoreTagEntry } from "./CoreTagEntry";

export type CoreStoryIndex = { assets: Array<CoreAssetReference>, contents: Array<CoreContentsEntry>, diagnostics: Array<CoreDiagnostic>, files: Array<CoreSourceFile>, graph: CoreGraphStats, replacePreviews: Array<CoreReplacePreview>, searchHits: Array<CoreSearchHit>, storyId: string, tags: Array<string>, tagEntries: Array<CoreTagEntry>, symbols: Array<CoreSymbol>, };
