// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreContentsEntryKind } from "./CoreContentsEntryKind";
import type { CoreDiagnosticSeverity } from "./CoreDiagnosticSeverity";

export type CoreContentsEntry = { count: number, detail: string | null, id: string, kind: CoreContentsEntryKind, label: string, passageId: string | null, severity: CoreDiagnosticSeverity | null, sourceId: string | null, };
