// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDiagnostic } from "./CoreDiagnostic";

export type CoreDiagnosticsPage = { diagnostics: Array<CoreDiagnostic>, nextCursor: string | null, revision: number, storyId: string, totalCount: number, };
