// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreContentsFacets = { all: number, asset: number, diagnostics: number, entryPoint: number, group: number, metadata: number, passage: number, problems: number, script: number, stylesheet: number, tag: number, variable: number, };
