// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSearchScope } from "./CoreSearchScope";

export type CoreReplacePreview = { after: string, before: string, end: number, line: number, matchText: string, passageId: string | null, replacement: string, scope: CoreSearchScope, sourceId: string, sourceName: string, start: number, };
