// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreExternalConflict = { field: string, message: string, passageId: string | null, path: string | null, storyId: string | null, };
