// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A revision-bound passage body. Persisted text stays session-owned; callers
 * request only the document they are actively displaying.
 */
export type CorePassageDocument = { passageId: string, revision: number, storyId: string, text: string, };
