// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreSearchQuery = { cursor: string | null, fuzzy: boolean, limit: number, matchCase: boolean, query: string, replacement: string | null, includePassageNames: boolean, includePassageText: boolean, includeScript: boolean, includeStylesheet: boolean, useRegexes: boolean, };
