// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphStats } from "./CoreGraphStats";

/**
 * Compact, always-bounded story facts for shell and route chrome.
 */
export type CoreStorySummary = { assetCount: number, characterCount: number, diagnosticCount: number, errorCount: number, graph: CoreGraphStats, missingAssetCount: number, passageCount: number, revision: number, storyId: string, tagCount: number, warningCount: number, wordCount: number, };
