// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact diagnostic counts for status chrome, after applying UI dismissals.
 */
export type CoreDiagnosticsSummary = { diagnosticCount: number, dismissedCount: number, errorCount: number, infoCount: number, revision: number, storyId: string, warningCount: number, };
