// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreReplacePreview } from "./CoreReplacePreview";
import type { CoreSearchHit } from "./CoreSearchHit";

export type CoreSearchPage = { nextCursor: string | null, replacePreviews: Array<CoreReplacePreview>, revision: number, searchHits: Array<CoreSearchHit>, storyId: string, totalCount: number, };
