// This file was generated by ts-rs. Do not edit this file manually.
import type { CoreSourceKind } from "./CoreSourceKind";

export type CoreSourceDocument = { kind: CoreSourceKind, revision: number, storyId: string, text: string, };
