// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CorePassageLinkFact = { broken: boolean, sourceId: string, targetId: string | null, targetName: string, };
