// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSourceRangeEncoding } from "./CoreSourceRangeEncoding";

export type CoreSourceSpan = { encoding: CoreSourceRangeEncoding, end: number, start: number, };
