// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreContentsEntry } from "./CoreContentsEntry";
import type { CoreContentsFacets } from "./CoreContentsFacets";

export type CoreContentsPage = { entries: Array<CoreContentsEntry>, facets: CoreContentsFacets, nextCursor: string | null, revision: number, storyId: string, totalCount: number, };
