// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDefinitionSymbolKind } from "./CoreDefinitionSymbolKind";
import type { CorePassageLocation } from "./CorePassageLocation";

export type CoreDefinitionResult = { "type": "unique", location: CorePassageLocation, } | { "type": "ambiguous", locations: Array<CorePassageLocation>, totalCount: number, } | { "type": "not_found" } | { "type": "unsupported", symbolKind: CoreDefinitionSymbolKind, } | { "type": "stale" };
