// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreContentsFilter = "all" | "asset" | "diagnostics" | "entryPoint" | "group" | "metadata" | "passage" | "problems" | "script" | "stylesheet" | "tag" | "variable";
