// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetInventoryEntry } from "./CoreAssetInventoryEntry";

export type CoreAssetsPage = { assets: Array<CoreAssetInventoryEntry>, nextCursor: string | null, revision: number, storyId: string, totalCount: number, };
