// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreAssetReference = { context: string, end: number, fragment: string | null, kind: string, line: number, original: string, passageId: string | null, path: string, query: string | null, sourceId: string, sourceName: string, start: number, };
