// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSearchScope } from "./CoreSearchScope";

export type CoreSearchHit = { after: string | null, before: string | null, end: number, excerpt: string, line: number, matchText: string, passageId: string | null, rank: number, replacement: string | null, scope: CoreSearchScope, sourceId: string, sourceName: string, start: number, };
