// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreHistoryKind = "batch" | "createStory" | "newPassage" | "deleteAsset" | "deletePassage" | "deleteStory" | "editPassage" | "externalChanges" | "importAsset" | "insertAsset" | "movePassage" | "renameAsset" | "renamePassage" | "renameStory" | "renameTag" | "replaceAsset" | "saveLayout" | "setStartPassage" | "storyDetails";
