// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorePassageReference } from "./CorePassageReference";
import type { CorePassageReferenceCoverage } from "./CorePassageReferenceCoverage";

export type CorePassageReferencesPage = { coverage: CorePassageReferenceCoverage, nextCursor: string | null, passageId: string, references: Array<CorePassageReference>, revision: number, storyId: string, totalCount: number, };
