// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreSemanticProvenance = { capabilityRevision: number, formatName: string | null, formatVersion: string | null, providerIdentifier: string, };
