// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetReference } from "./CoreAssetReference";
import type { CoreDiagnostic } from "./CoreDiagnostic";
import type { CorePassageLinkFact } from "./CorePassageLinkFact";
import type { CoreSymbol } from "./CoreSymbol";

export type CorePassageLocalFacts = { assetReferences: Array<CoreAssetReference>, characterCount: number, diagnostics: Array<CoreDiagnostic>, excerpt: string, isEmpty: boolean, lineCount: number, links: Array<CorePassageLinkFact>, passageId: string, revision: number, storyId: string, symbols: Array<CoreSymbol>, wordCount: number, };
