// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreExternalConflict } from "./CoreExternalConflict";
import type { CoreExternalIngestOutcome } from "./CoreExternalIngestOutcome";
import type { CoreSessionStatus } from "./CoreSessionStatus";
import type { PatchBatch } from "./PatchBatch";

export type CoreExternalIngestResult = { batch: PatchBatch | null, conflicts: Array<CoreExternalConflict>, historyRecorded: boolean, outcome: CoreExternalIngestOutcome, status: CoreSessionStatus, };
