// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDefinitionSymbolKind } from "./CoreDefinitionSymbolKind";

export type CoreDefinitionQuery = { expectedRevision: number, storyId: string, symbolKind: CoreDefinitionSymbolKind, name: string, };
