// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreContentsFilter } from "./CoreContentsFilter";
import type { CoreContentsSort } from "./CoreContentsSort";

export type CoreContentsQuery = { cursor: string | null, filter: CoreContentsFilter, limit: number, query: string | null, sort: CoreContentsSort, };
