// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDocumentEntry } from "./CoreDocumentEntry";

export type CoreDocumentPage = { documents: Array<CoreDocumentEntry>, nextCursor: string | null, revision: number, storyId: string, totalCount: number, };
