// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSearchScope } from "./CoreSearchScope";
import type { CoreSymbolKind } from "./CoreSymbolKind";

export type CoreSymbol = { end: number, excerpt: string, kind: CoreSymbolKind, line: number, name: string, passageId: string | null, scope: CoreSearchScope, sourceId: string, sourceName: string, start: number, };
