// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreAssetReference = { end: number, kind: string, line: number, passageId: string | null, path: string, sourceId: string, sourceName: string, start: number, };
