// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphLayoutSource } from "./CoreGraphLayoutSource";
import type { CoreRect } from "./CoreRect";

export type CoreGraphNode = { bounds: CoreRect, brokenLinkCount: number, excerpt: string, id: string, incomingCount: number, isEmpty: boolean, isOrphan: boolean, isStart: boolean, isUnreachable: boolean, layoutSource: CoreGraphLayoutSource, name: string, outgoingCount: number, selfLinkCount: number, tags: Array<string>, };
