// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetInventoryEntry } from "./CoreAssetInventoryEntry";
import type { CoreRect } from "./CoreRect";
import type { PassagePatch } from "./PassagePatch";
import type { PassageSnapshot } from "./PassageSnapshot";
import type { StoryMetadataPatch } from "./StoryMetadataPatch";
import type { StorySnapshot } from "./StorySnapshot";

export type CoreExternalChange = { "type": "deleteAsset", path: string, } | { "type": "deletePassage", passage_id: string, story_id: string, } | { "type": "deleteStory", story_id: string, } | { "type": "upsertPassage", passage: PassageSnapshot, story_id: string, } | { "type": "upsertAsset", asset: CoreAssetInventoryEntry, } | { "type": "upsertStory", story: StorySnapshot, } | { "type": "updatePassage", changes: PassagePatch, passage_id: string, story_id: string, } | { "type": "updatePassageLayout", layout: CoreRect | null, passage_id: string, story_id: string, } | { "type": "updateProjectLayout", layout_json: string, } | { "type": "updateStoryMetadata", changes: StoryMetadataPatch, story_id: string, } | { "type": "updateStoryStartPassage", passage_id: string, story_id: string, } | { "type": "updateStoryScript", script: string, story_id: string, } | { "type": "updateStoryStylesheet", story_id: string, stylesheet: string, };
