// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreStoryIndexOptions = { fuzzy: boolean, includeAssets: boolean, includePassageNames: boolean, includePassageText: boolean, includeScript: boolean, includeStylesheet: boolean, includeTags: boolean, includeVariables: boolean, matchCase: boolean, query: string | null, replacement: string | null, useRegexes: boolean, };
