// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassageSnapshot } from "./PassageSnapshot";
import type { StorySnapshot } from "./StorySnapshot";

export type CoreExternalChange = { "type": "deletePassage", passage_id: string, story_id: string, } | { "type": "deleteStory", story_id: string, } | { "type": "upsertPassage", passage: PassageSnapshot, story_id: string, } | { "type": "upsertStory", story: StorySnapshot, } | { "type": "updateStoryScript", script: string, story_id: string, } | { "type": "updateStoryStylesheet", story_id: string, stylesheet: string, };
