// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDiagnosticSeverity } from "./CoreDiagnosticSeverity";
import type { CoreQuickFix } from "./CoreQuickFix";

export type CoreDiagnostic = { code: string, end: number, line: number, message: string, passageId: string | null, quickFixes: Array<CoreQuickFix>, severity: CoreDiagnosticSeverity, sourceId: string, start: number, };
