// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanFailure } from "./RefactorPlanFailure";
import type { RefactorPlanSummary } from "./RefactorPlanSummary";

export type PlanDiagnosticFixesResult = { "type": "complete", summary: RefactorPlanSummary, } | { "type": "failure", failure: RefactorPlanFailure, };
