// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Narrow, non-executable input for a project-wide replacement plan.
 */
export type PlanProjectReplaceRequest = { storyId: string, query: string, replacement: string, includePassageNames: boolean, includePassageText: boolean, includeScript: boolean, includeStylesheet: boolean, matchCase: boolean, useRegexes: boolean, };
