// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanFailure } from "./RefactorPlanFailure";
import type { RefactorPlanSummary } from "./RefactorPlanSummary";
import type { RefactorPlanningProgress } from "./RefactorPlanningProgress";
import type { RefactorPlanningTaskHandle } from "./RefactorPlanningTaskHandle";

export type PlanProjectReplaceResult = { "type": "pending", task: RefactorPlanningTaskHandle, progress: RefactorPlanningProgress, } | { "type": "complete", summary: RefactorPlanSummary, } | { "type": "cancelled" } | { "type": "failure", failure: RefactorPlanFailure, };
