// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanFailure } from "./RefactorPlanFailure";
import type { RefactorPlanningTaskHandle } from "./RefactorPlanningTaskHandle";

export type PlanPassageRenameBeginResult = { "type": "begun", task: RefactorPlanningTaskHandle, } | { "type": "failure", failure: RefactorPlanFailure, };
