// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The narrow public input for the Rust-owned passage rename operation.
 */
export type PlanPassageRenameRequest = { storyId: string, passageId: string, afterName: string, };
