// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorAffectedEntityKind } from "./RefactorAffectedEntityKind";

export type RefactorAffectedEntity = { kind: RefactorAffectedEntityKind, storyId: string | null, entityId: string, };
