// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorBufferPrecondition } from "./RefactorBufferPrecondition";
import type { RefactorExternalPrecondition } from "./RefactorExternalPrecondition";
import type { RefactorProviderPrecondition } from "./RefactorProviderPrecondition";

/**
 * Trusted runtime state captured by the project host. Review components never
 * construct this value directly.
 */
export type RefactorRuntimeState = { projectRevision: number, buffers: Array<RefactorBufferPrecondition>, external: RefactorExternalPrecondition | null, provider: RefactorProviderPrecondition | null, };
