// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanFailureCode } from "./RefactorPlanFailureCode";

export type RefactorPlanFailure = { code: RefactorPlanFailureCode, message: string, };
