// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorAffectedEntity } from "./RefactorAffectedEntity";
import type { RefactorPlanChangeKind } from "./RefactorPlanChangeKind";
import type { RefactorPlanValue } from "./RefactorPlanValue";
import type { RefactorSourceLocation } from "./RefactorSourceLocation";

export type RefactorPlanDetail = { changeId: string, groupId: string | null, kind: RefactorPlanChangeKind, affectedEntity: RefactorAffectedEntity, description: string, before: RefactorPlanValue | null, after: RefactorPlanValue | null, dependencies: Array<string>, location: RefactorSourceLocation | null, };
