// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorSourceLocation } from "./RefactorSourceLocation";

export type RefactorAppliedTextEdit = { expectedText: string, replacementText: string, source: RefactorSourceLocation, };
