// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorSourceKind } from "./RefactorSourceKind";
import type { RefactorSourceSpan } from "./RefactorSourceSpan";

export type RefactorSourceLocation = { storyId: string, sourceKind: RefactorSourceKind, sourceId: string, revision: number, span: RefactorSourceSpan, };
