// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanCursor } from "./RefactorPlanCursor";
import type { RefactorPlanDetail } from "./RefactorPlanDetail";

export type RefactorPlanDetailPage = { changes: Array<RefactorPlanDetail>, nextCursor: RefactorPlanCursor | null, };
