// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefactorSelectionCapabilities = { all: boolean, exclusions: boolean, groups: boolean, only: boolean, };
