// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanCursor } from "./RefactorPlanCursor";
import type { RefactorSelectionCapabilities } from "./RefactorSelectionCapabilities";

export type RefactorPlanSummary = { planId: string, planDigest: string, projectRevision: number, operationKind: string, affectedEntityCount: number, changeCount: number, validationFailures: Array<string>, coverage: string, selectionCapabilities: RefactorSelectionCapabilities, firstDetailCursor: RefactorPlanCursor,
/**
 * JavaScript-safe epoch milliseconds.
 */
expiresAtEpochMs: number, };
