// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefactorPlanSelection = { "type": "all" } | { "type": "allExcept", changeIds: Array<string>, } | { "type": "only", changeIds: Array<string>, } | { "type": "groups", groupIds: Array<string>, exclusions: Array<string>, };
