// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorAppliedTextEdit } from "./RefactorAppliedTextEdit";

/**
 * Exact selected text edits, emitted only after a successful atomic apply.
 */
export type RefactorApplyReceipt = { textEdits: Array<RefactorAppliedTextEdit>, };
