// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchBatch } from "./PatchBatch";
import type { RefactorApplyReceipt } from "./RefactorApplyReceipt";
import type { RefactorPlanFailure } from "./RefactorPlanFailure";

export type RefactorPlanApplyResult = { "type": "applied", batch: PatchBatch, receipt: RefactorApplyReceipt, } | { "type": "failure", failure: RefactorPlanFailure, };
