// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefactorPlanFailureCode = "stale-project-revision" | "buffer-changed" | "plan-expired" | "plan-evicted" | "provider-changed" | "persistence-conflict" | "invalid-selection" | "selection-too-large" | "plan-too-large" | "invalid-plan" | "digest-mismatch";
