// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassageSnapshot } from "./PassageSnapshot";
import type { StoryMetadataPatch } from "./StoryMetadataPatch";

export type RefactorPlanValue = { "type": "text", value: string, } | { "type": "passageName", value: string, } | { "type": "passageId", value: string, } | { "type": "passage", passage: PassageSnapshot, } | { "type": "storyMetadata", value: StoryMetadataPatch, } | { "type": "projectName", value: string, };
