// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactorPlanDetailPage } from "./RefactorPlanDetailPage";
import type { RefactorPlanFailure } from "./RefactorPlanFailure";

export type RefactorPlanDetailResult = { "type": "page", page: RefactorPlanDetailPage, } | { "type": "failure", failure: RefactorPlanFailure, };
