// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefactorPlanChangeKind = "text-edit" | "rename-passage" | "add-passage" | "remove-passage" | "set-start-passage" | "update-story-metadata" | "update-project-metadata";
