// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PassageSnapshot } from "./PassageSnapshot";

export type StorySnapshot = { id: string, ifid: string, name: string, passages: Array<PassageSnapshot>, script: string, snapToGrid: boolean, startPassageId: string, storyFormat: string, storyFormatVersion: string, stylesheet: string, tags: Array<string>, tagColors: { [key in string]?: string }, zoom: number, };
