// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoryMetadataPatch = { name: string | null, snapToGrid: boolean | null, storyFormat: string | null, storyFormatVersion: string | null, tagColors: { [key in string]?: string } | null, tags: Array<string> | null, zoom: number | null, };
